import type { PrismaClient } from '@deckgauge/db';
import type { IntelligenceSchema } from '@deckgauge/shared';
import { resolveScope } from './scope/resolve-scope.js';
import { listTablesForSourceTypes, type SourceType } from './scope/catalog.js';

// Column lists extracted verbatim from clickhouse/schemas/*.sql.
// If the DDL changes, regenerate this map by re-reading those files.
const TABLE_COLUMNS: Readonly<
  Record<string, ReadonlyArray<{ name: string; type: string }>>
> = Object.freeze({
  jira_issues: [
    { name: 'id', type: 'String' },
    { name: 'key', type: 'String' },
    { name: 'project_key', type: 'String' },
    { name: 'project_name', type: 'String' },
    { name: 'issue_type', type: 'String' },
    { name: 'parent_key', type: 'Nullable(String)' },
    { name: 'epic_key', type: 'Nullable(String)' },
    { name: 'epic_summary', type: 'Nullable(String)' },
    { name: 'summary', type: 'String' },
    { name: 'description', type: 'String' },
    { name: 'priority', type: 'String' },
    { name: 'labels', type: 'Array(String)' },
    { name: 'components', type: 'Array(String)' },
    { name: 'fix_versions', type: 'Array(String)' },
    { name: 'assignee', type: 'Nullable(String)' },
    { name: 'assignee_email', type: 'Nullable(String)' },
    { name: 'reporter', type: 'Nullable(String)' },
    { name: 'status', type: 'String' },
    { name: 'status_category', type: 'String' },
    { name: 'resolution', type: 'Nullable(String)' },
    { name: 'story_points', type: 'Nullable(Float32)' },
    { name: 'original_estimate_s', type: 'Nullable(UInt32)' },
    { name: 'time_spent_s', type: 'Nullable(UInt32)' },
    { name: 'sprint_id', type: 'Nullable(String)' },
    { name: 'sprint_name', type: 'Nullable(String)' },
    { name: 'sprint_state', type: 'Nullable(String)' },
    { name: 'created_at', type: 'DateTime' },
    { name: 'updated_at', type: 'DateTime' },
    { name: 'resolved_at', type: 'Nullable(DateTime)' },
    { name: 'due_date', type: 'Nullable(Date)' },
    { name: 'custom_fields', type: 'String' },
    { name: 'instance_url', type: 'String' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  jira_transitions: [
    { name: 'id', type: 'String' },
    { name: 'issue_key', type: 'String' },
    { name: 'project_key', type: 'String' },
    { name: 'issue_type', type: 'String' },
    { name: 'assignee', type: 'Nullable(String)' },
    { name: 'from_status', type: 'String' },
    { name: 'from_category', type: 'String' },
    { name: 'to_status', type: 'String' },
    { name: 'to_category', type: 'String' },
    { name: 'transitioned_by', type: 'Nullable(String)' },
    { name: 'transitioned_at', type: 'DateTime' },
    { name: 'time_in_prev_status_s', type: 'UInt32' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  github_issues: [
    { name: 'id', type: 'String' },
    { name: 'repo_full_name', type: 'String' },
    { name: 'number', type: 'UInt32' },
    { name: 'instance_id', type: 'String' },
    { name: 'title', type: 'String' },
    { name: 'body', type: 'String' },
    { name: 'state', type: 'String' },
    { name: 'labels', type: 'Array(String)' },
    { name: 'assignee_login', type: 'Nullable(String)' },
    { name: 'assignee_name', type: 'Nullable(String)' },
    { name: 'milestone_number', type: 'Nullable(UInt32)' },
    { name: 'milestone_title', type: 'Nullable(String)' },
    { name: 'linked_ticket_keys', type: 'Array(String)' },
    { name: 'is_pull_request', type: 'UInt8' },
    { name: 'pull_request_number', type: 'Nullable(UInt32)' },
    { name: 'created_at', type: 'DateTime' },
    { name: 'updated_at', type: 'DateTime' },
    { name: 'closed_at', type: 'Nullable(DateTime)' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  github_milestones: [
    { name: 'id', type: 'String' },
    { name: 'repo_full_name', type: 'String' },
    { name: 'number', type: 'UInt32' },
    { name: 'instance_id', type: 'String' },
    { name: 'title', type: 'String' },
    { name: 'description', type: 'String' },
    { name: 'state', type: 'String' },
    { name: 'due_on', type: 'Nullable(DateTime)' },
    { name: 'open_issues', type: 'UInt32' },
    { name: 'closed_issues', type: 'UInt32' },
    { name: 'created_at', type: 'DateTime' },
    { name: 'updated_at', type: 'DateTime' },
    { name: 'closed_at', type: 'Nullable(DateTime)' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  github_pull_requests: [
    { name: 'id', type: 'String' },
    { name: 'repo_full_name', type: 'String' },
    { name: 'number', type: 'UInt32' },
    { name: 'instance_id', type: 'String' },
    { name: 'title', type: 'String' },
    { name: 'body', type: 'String' },
    { name: 'state', type: 'String' },
    { name: 'is_draft', type: 'UInt8' },
    { name: 'base_branch', type: 'String' },
    { name: 'head_branch', type: 'String' },
    { name: 'labels', type: 'Array(String)' },
    { name: 'milestone_title', type: 'Nullable(String)' },
    { name: 'author_login', type: 'String' },
    { name: 'author_name', type: 'Nullable(String)' },
    { name: 'requested_reviewers', type: 'Array(String)' },
    { name: 'additions', type: 'UInt32' },
    { name: 'deletions', type: 'UInt32' },
    { name: 'changed_files', type: 'UInt16' },
    { name: 'commit_count', type: 'UInt16' },
    { name: 'created_at', type: 'DateTime' },
    { name: 'updated_at', type: 'DateTime' },
    { name: 'merged_at', type: 'Nullable(DateTime)' },
    { name: 'closed_at', type: 'Nullable(DateTime)' },
    { name: 'first_review_at', type: 'Nullable(DateTime)' },
    { name: 'first_approval_at', type: 'Nullable(DateTime)' },
    { name: 'cycle_time_hours', type: 'Nullable(Float32)' },
    { name: 'review_time_hours', type: 'Nullable(Float32)' },
    { name: 'approval_time_hours', type: 'Nullable(Float32)' },
    { name: 'merge_time_hours', type: 'Nullable(Float32)' },
    { name: 'ai_assisted', type: 'UInt8' },
    { name: 'ai_confidence', type: 'Nullable(Float32)' },
    { name: 'ai_signals', type: 'String' },
    { name: 'linked_ticket_keys', type: 'Array(String)' },
    { name: 'merge_commit_sha', type: 'Nullable(String)' },
    { name: 'merged_by_login', type: 'Nullable(String)' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  github_commits: [
    { name: 'id', type: 'String' },
    { name: 'sha', type: 'String' },
    { name: 'repo_full_name', type: 'String' },
    { name: 'instance_id', type: 'String' },
    { name: 'author_login', type: 'Nullable(String)' },
    { name: 'author_name', type: 'String' },
    { name: 'author_email', type: 'String' },
    { name: 'committer_login', type: 'Nullable(String)' },
    { name: 'committer_name', type: 'String' },
    { name: 'message', type: 'String' },
    { name: 'message_subject', type: 'String' },
    { name: 'additions', type: 'UInt32' },
    { name: 'deletions', type: 'UInt32' },
    { name: 'changed_files', type: 'UInt16' },
    { name: 'branch', type: 'Nullable(String)' },
    { name: 'pull_request_number', type: 'Nullable(UInt32)' },
    { name: 'is_merge_commit', type: 'UInt8' },
    { name: 'committed_at', type: 'DateTime' },
    { name: 'ai_assisted', type: 'UInt8' },
    { name: 'ai_confidence', type: 'Nullable(Float32)' },
    { name: 'ai_signals', type: 'String' },
    { name: 'linked_ticket_keys', type: 'Array(String)' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  gitlab_merge_requests: [
    { name: 'id', type: 'String' },
    { name: 'project_path', type: 'String' },
    { name: 'iid', type: 'UInt32' },
    { name: 'instance_id', type: 'String' },
    { name: 'title', type: 'String' },
    { name: 'description', type: 'String' },
    { name: 'state', type: 'String' },
    { name: 'is_draft', type: 'UInt8' },
    { name: 'source_branch', type: 'String' },
    { name: 'target_branch', type: 'String' },
    { name: 'labels', type: 'Array(String)' },
    { name: 'milestone_title', type: 'Nullable(String)' },
    { name: 'author_username', type: 'String' },
    { name: 'author_name', type: 'Nullable(String)' },
    { name: 'assignee_username', type: 'Nullable(String)' },
    { name: 'reviewers', type: 'Array(String)' },
    { name: 'additions', type: 'UInt32' },
    { name: 'deletions', type: 'UInt32' },
    { name: 'changed_files', type: 'UInt16' },
    { name: 'created_at', type: 'DateTime' },
    { name: 'updated_at', type: 'DateTime' },
    { name: 'merged_at', type: 'Nullable(DateTime)' },
    { name: 'closed_at', type: 'Nullable(DateTime)' },
    { name: 'first_review_at', type: 'Nullable(DateTime)' },
    { name: 'first_approval_at', type: 'Nullable(DateTime)' },
    { name: 'cycle_time_hours', type: 'Nullable(Float32)' },
    { name: 'review_time_hours', type: 'Nullable(Float32)' },
    { name: 'ai_assisted', type: 'UInt8' },
    { name: 'ai_confidence', type: 'Nullable(Float32)' },
    { name: 'ai_signals', type: 'String' },
    { name: 'linked_ticket_keys', type: 'Array(String)' },
    { name: 'merged_by_username', type: 'Nullable(String)' },
    { name: 'merge_commit_sha', type: 'Nullable(String)' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  gitlab_commits: [
    { name: 'id', type: 'String' },
    { name: 'sha', type: 'String' },
    { name: 'project_path', type: 'String' },
    { name: 'instance_id', type: 'String' },
    { name: 'author_name', type: 'String' },
    { name: 'author_email', type: 'String' },
    { name: 'committer_name', type: 'String' },
    { name: 'message', type: 'String' },
    { name: 'message_subject', type: 'String' },
    { name: 'additions', type: 'UInt32' },
    { name: 'deletions', type: 'UInt32' },
    { name: 'changed_files', type: 'UInt16' },
    { name: 'merge_request_iid', type: 'Nullable(UInt32)' },
    { name: 'is_merge_commit', type: 'UInt8' },
    { name: 'committed_at', type: 'DateTime' },
    { name: 'ai_assisted', type: 'UInt8' },
    { name: 'ai_confidence', type: 'Nullable(Float32)' },
    { name: 'ai_signals', type: 'String' },
    { name: 'linked_ticket_keys', type: 'Array(String)' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  ado_work_items: [
    { name: 'id', type: 'String' },
    { name: 'ado_id', type: 'UInt32' },
    { name: 'org_url', type: 'String' },
    { name: 'project', type: 'String' },
    { name: 'area_path', type: 'String' },
    { name: 'iteration_path', type: 'String' },
    { name: 'work_item_type', type: 'String' },
    { name: 'title', type: 'String' },
    { name: 'description', type: 'String' },
    { name: 'state', type: 'String' },
    { name: 'reason', type: 'Nullable(String)' },
    { name: 'priority', type: 'Nullable(UInt8)' },
    { name: 'assigned_to', type: 'Nullable(String)' },
    { name: 'assigned_to_email', type: 'Nullable(String)' },
    { name: 'created_by', type: 'Nullable(String)' },
    { name: 'changed_by', type: 'Nullable(String)' },
    { name: 'parent_ado_id', type: 'Nullable(UInt32)' },
    { name: 'story_points', type: 'Nullable(Float32)' },
    { name: 'remaining_work', type: 'Nullable(Float32)' },
    { name: 'completed_work', type: 'Nullable(Float32)' },
    { name: 'tags', type: 'Array(String)' },
    { name: 'sprint_name', type: 'Nullable(String)' },
    { name: 'sprint_path', type: 'Nullable(String)' },
    { name: 'custom_fields', type: 'String' },
    { name: 'created_at', type: 'DateTime' },
    { name: 'updated_at', type: 'DateTime' },
    { name: 'closed_at', type: 'Nullable(DateTime)' },
    { name: 'instance_id', type: 'String' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  ado_pull_requests: [
    { name: 'id', type: 'String' },
    { name: 'pr_id', type: 'UInt32' },
    { name: 'org_url', type: 'String' },
    { name: 'project', type: 'String' },
    { name: 'repo_name', type: 'String' },
    { name: 'title', type: 'String' },
    { name: 'description', type: 'String' },
    { name: 'status', type: 'String' },
    { name: 'is_draft', type: 'UInt8' },
    { name: 'source_branch', type: 'String' },
    { name: 'target_branch', type: 'String' },
    { name: 'labels', type: 'Array(String)' },
    { name: 'created_by_login', type: 'String' },
    { name: 'created_by_name', type: 'Nullable(String)' },
    { name: 'reviewers', type: 'Array(String)' },
    { name: 'additions', type: 'UInt32' },
    { name: 'deletions', type: 'UInt32' },
    { name: 'created_at', type: 'DateTime' },
    { name: 'updated_at', type: 'DateTime' },
    { name: 'closed_at', type: 'Nullable(DateTime)' },
    { name: 'first_vote_at', type: 'Nullable(DateTime)' },
    { name: 'cycle_time_hours', type: 'Nullable(Float32)' },
    { name: 'review_time_hours', type: 'Nullable(Float32)' },
    { name: 'ai_assisted', type: 'UInt8' },
    { name: 'ai_confidence', type: 'Nullable(Float32)' },
    { name: 'ai_signals', type: 'String' },
    { name: 'linked_ticket_keys', type: 'Array(String)' },
    { name: 'instance_id', type: 'String' },
    { name: 'synced_at', type: 'DateTime' },
  ],
  ado_commits: [
    { name: 'id', type: 'String' },
    { name: 'sha', type: 'String' },
    { name: 'org_url', type: 'String' },
    { name: 'project', type: 'String' },
    { name: 'repo_id', type: 'String' },
    { name: 'repo_name', type: 'String' },
    { name: 'repo_url', type: 'String' },
    { name: 'instance_id', type: 'String' },
    { name: 'author_login', type: 'Nullable(String)' },
    { name: 'author_name', type: 'String' },
    { name: 'author_email', type: 'String' },
    { name: 'committer_name', type: 'String' },
    { name: 'committer_email', type: 'String' },
    { name: 'message', type: 'String' },
    { name: 'message_subject', type: 'String' },
    { name: 'additions', type: 'UInt32' },
    { name: 'deletions', type: 'UInt32' },
    { name: 'changed_files', type: 'UInt16' },
    { name: 'branch', type: 'Nullable(String)' },
    { name: 'pull_request_id', type: 'Nullable(UInt32)' },
    { name: 'is_merge_commit', type: 'UInt8' },
    { name: 'committed_at', type: 'DateTime' },
    { name: 'ai_assisted', type: 'UInt8' },
    { name: 'ai_confidence', type: 'Nullable(Float32)' },
    { name: 'ai_signals', type: 'String' },
    { name: 'linked_ticket_keys', type: 'Array(String)' },
    { name: 'synced_at', type: 'DateTime' },
  ],
});

export async function buildSchemaPayload(
  prisma: PrismaClient,
  boardId: string
): Promise<IntelligenceSchema> {
  const scope = await resolveScope(prisma, boardId);
  const sourceTypes: SourceType[] = [];
  if (scope.github.length > 0) sourceTypes.push('github');
  if (scope.jira.length > 0) sourceTypes.push('jira');
  if (scope.ado.length > 0) sourceTypes.push('ado');
  if (scope.gitlab.length > 0) sourceTypes.push('gitlab');

  const tableNames = listTablesForSourceTypes(sourceTypes);
  return {
    tables: tableNames.map((name) => ({
      name,
      columns: [...(TABLE_COLUMNS[name] ?? [])],
    })),
    scope: {
      repos: scope.github,
      jiraProjectKeys: scope.jira,
      adoProjects: scope.ado,
      gitlabProjectPaths: scope.gitlab,
    },
  };
}
